spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  security:
    oauth2:
      client:
        registration:
          my-app: # Это фактически registrationId которое используется по коду и также используется в redirect-uri ниже
            provider: auth0 # название провайдера который мы зарегистрируем позже ниже
            client-id: mTRDwuz9sT3GkkA8SHf2pt4eNHXqnpYB
            client-secret: Oc0TFAqcGLVdBJBebCqEqIzy9Rnvc1PsSgTPrDuh4-cDVhWhKjkcL07ZAQze62bk
            client-authentication-type: method
            authorization-grant-type: authorization_code
            scope: profile,openid,email,phone,address
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}" #здесь необходим шаблон как указано,
              #Spring Secuirity автоматом резолвит его опираясь на registrationId
              # этот шаблон нужен для определения callback url
              # callback url в последствии мы должны зарегистрировать на стороне Auth0
            # в настройках приложения Allowed Callback URLs

            client-name: OAuth client app # Просто логическое имя клиенту
        provider:
          auth0:
            authorization-uri: https://activx.auth0.com/authorize
            token-uri: https://activx.auth0.com/oauth/token
            # этот эндпоинт для  openid может не использоваться и его можно убрать
            # но тогда мы не сможем обращатся в наших authorities к объекту userInfo т.к. он будет null
            # к примеру в строке 90 OAuth3ClientApplication строка проверки наличия аттрибута
            # она могла быть без использвания idToken а с использованием userInfo
            #   .filter(userAuthority -> userAuthority.getUserInfo().containsClaim(attributeName))
            # но если мы уберем user-info-uri то getUserInfo вернет null
            user-info-uri: https://activx.auth0.com/userinfo
            jwk-set-uri: https://activx.auth0.com/.well-known/jwks.json
            user-name-attribute: sub # атрибут id token (или user info объекта) для определения какое поле будет userName
