spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: someid
            client-secret: somesecret

